version: '3.8'

services:
  my-service:
    container_name: my-service
    build: 
      context: .
      target: production
    ports:
      - "3000:3000"

  my-service-dev:
    container_name: my-service-dev
    restart: unless-stopped
    build: 
      context: ./src
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/project
