version: '3.8'

services:
  my-service:
    container_name: my-service
    build: 
      context: .
      target: production
    ports:
      - "3000:1234"

  my-service-dev:
    container_name: my-service-dev
    restart: unless-stopped
    build: 
      context: .
      target: dev
    ports:
      - "1234:1234"
    volumes:
      - .:/project
